version: '3.3'

volumes:
  postgres-data:
    driver: local

services:
  postgres:
    image: postgres:15
    container_name: tspcompat_db
    restart: unless-stopped
    ports:
      - "5450:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: tspcompat
      POSTGRES_USER: tspcompat
      POSTGRES_PASSWORD: tspcompat